pipeline {

    agent any
 	parameters {
        string(defaultValue: "pratik.p.hatankar@oracle.com", description: 'What environment?', name: 'EmailRecipient')
        // choices are newline separated
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'Maven'
        jdk 'JDK'
    }
    stages {
        stage ('Checkout'){
            steps {
             git (
                    url: 'https://github.com/pratikhatankar23/devopsrepo.git',
                    credentialsId: '3e24aaf5-0495-4045-8947-0c029e505ba2'
                )
			
            }
   	    }
        stage('Build') {
            steps {
	       bat "echo ${params.EmailRecipient}"
	       bat "echo ${params.region}"    
               bat 'mvn clean package sonar:sonar -Dsonar.host.url=http://localhost:9000/ -DproxySet=true -DproxyHost=www-proxy.us.oracle.com -DproxyPort=80' -f CounterWebApp/pom.xml
		  //sh 'mvn clean package -DproxySet=true -DproxyHost=www-proxy.us.oracle.com -DproxyPort=80'
		   	nexusArtifactUploader(
    			nexusVersion: 'nexus3',
    			protocol: 'http',
    			nexusUrl: 'localhost:8081',
    			groupId: 'com.mkyong',
    			version: '1.0-SNAPSHOT',
    			repository: 'maven-snapshots',
    			credentialsId: '491ecec4-dba4-4caa-b4a6-a150a24f3eb4',
    			artifacts: [
        		[artifactId: 'CounterWebApp',
         		classifier: '',
         		file: '/CounterWebApp/target/CounterWebApp.war',
         		type: 'war']
    			]
 		)
           
   	    }
            
        }
		
		stage ('success'){
            steps {
                script {
                    currentBuild.result = 'SUCCESS'
                }
            }
        }
		
    }
	post {
        failure {
            script {
                currentBuild.result = 'FAILURE'
            }
        }

        always {
            step([$class: 'Mailer',
                notifyEveryUnstableBuild: true,
                recipients: "${params.EmailRecipient}",
                sendToIndividuals: true])
        }
    }
}